### ISSUE TITLE
Version 0.24.6 breaks build

### ISSUE THREAD

**Issue by cmenzi** [nuke-build/nuke#451]
### Description

After updating `Nuke.Common` to version `0.24.6` build does not work anymore.

### Relevant log output

```
C:\Users\XXXX\.nuget\packages\nuke.common\0.24.6\build\netcore\Nuke.MSBuildTasks.targets(24,5): error MSB4062: The "Nuke.MSBuildTasks.ExternalFilesTask" task could not be loaded from the assembly C:\Users\XXXX\.nuget\packages\nuke.common\0.24.6\build\netcore\\Nuke.MSBuildTasks.dll. Could not load file or assembly 'C:\Users\XXXX\.nuget\packages\nuke.common\0.24.6\build\netcore\Nuke.MSBuildTasks.dll'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Data\src\build\_build.csproj]
```

**Comment by ayfie-frank-gynnild** [comment]
I experience the same issue here.

**Comment by krankenbro** [comment]
The same issue

**Comment by fvaillancourt** [comment]
Same issue
The netcore directory only has this file: Nuke.MSBuildTasks.targets
While netfx has many, including Nuke.MSBuildTasks.dll.
Not sure if it should point to it or there are missing files in netcore.

**Comment by matkoch** [comment]
@snowbirder @fvaillancourt please star the project.

**Comment by ayfie-frank-gynnild** [comment]
Done :-) Great project!

**Comment by krankenbro** [comment]
0.24.7 the issue is still actual
![image](https://user-images.githubusercontent.com/42555001/77662704-e1a0cf00-6f84-11ea-86bb-91b156231d71.png)

**Comment by matkoch** [comment]
@krankenbro it's a different exception message, so no, it's not the same issue. It is described [here](https://github.com/nuke-build/nuke/issues/348) with a known workaround.

As a side note, next time please don't paste just images of stack traces that I can barely read. Having stack traces in text form is important to do efficient analysis.

**Comment by matkoch** [comment]
Also, GitHub has a search feature :) https://github.com/nuke-build/nuke/issues?q=json+path+name+is%3Aopen

<blockquote><img src="https://avatars1.githubusercontent.com/u/26774874?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/nuke">nuke-build/nuke</a></strong></div><div>The AKEless Build System for C#/.NET. Contribute to nuke-build/nuke development by creating an account on GitHub.</div></blockquote>

**Comment by robsonj** [comment]
I believe I am experiencing the same issue, the workaround does not seem to help my situation. Hopefully of help, here is the stack trace...
```
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018: The "CodeGenerationTask" task failed unexpectedly.
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018: Newtonsoft.Json.JsonSerializationException: Required property 'Name' not found in JSON. Path '', line 8, position 1.
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.CodeGeneration.ToolSerializer.Load(String file) in /bitrise/src/source/Nuke.CodeGeneration/ToolSerializer.cs:line 33
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.CodeGeneration.CodeGenerator.GenerateCode(String specificationFile, Func`2 outputFileProvider, Func`2 namespaceProvider, Func`2 sourceFileProvider) in /bitrise/src/source/Nuke.CodeGeneration/CodeGenerator.cs:line 40
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.<>c__DisplayClass20_0.<ExecuteInner>b__6(String x) in /bitrise/src/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 59
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /bitrise/src/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.MSBuildTasks.CodeGenerationTask.ExecuteInner() in /bitrise/src/source/Nuke.MSBuildTasks/CodeGenerationTask.cs:line 57
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Nuke.MSBuildTasks.ContextAwareTask.Execute() in /bitrise/src/source/Nuke.MSBuildTasks/ContextAwareTask.cs:line 76
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\jrobson\.nuget\packages\nuke.common\0.24.7\build\netfx\Nuke.MSBuildTasks.targets(43,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by ghost** [comment]
I link here same issue #480 (blocked issue).
We should open this or the other one again. since this issue still exists in version 0.24.9.
The current issue is that the path is broken and contains `\\` before the .dll file name.
